language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development
  
 

after_success:
- bash <(curl -s https://codecov.io/bash) -t 1036eb64-2d96-44c6-b132-0dde4e7dfcca # replace the 1036eb64-2d96-44c6-b132-0dde4e7dfcca with your repository's token obtained by CodeCov
